// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5z9AuF0jdoHRNBBHIh1b8hAuDqt7spkc',
    appId: '1:297260992136:web:04ce12bf650d149ab1013d',
    messagingSenderId: '297260992136',
    projectId: 'ecorommece-app-kit',
    authDomain: 'ecorommece-app-kit.firebaseapp.com',
    storageBucket: 'ecorommece-app-kit.appspot.com',
    measurementId: 'G-GRWB6XNS6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe4Y7Yv6KRe659Bt9Cw6CUA5KzZFl5zxM',
    appId: '1:297260992136:android:a97b07fc6fae9298b1013d',
    messagingSenderId: '297260992136',
    projectId: 'ecorommece-app-kit',
    storageBucket: 'ecorommece-app-kit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuvaLvSPNl4B4k45hTkHe4cDxlD3jlspo',
    appId: '1:297260992136:ios:450fa309e17f020ab1013d',
    messagingSenderId: '297260992136',
    projectId: 'ecorommece-app-kit',
    storageBucket: 'ecorommece-app-kit.appspot.com',
    iosBundleId: 'com.example.ecorommeceAppKit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuvaLvSPNl4B4k45hTkHe4cDxlD3jlspo',
    appId: '1:297260992136:ios:906ed90ed9ade6fcb1013d',
    messagingSenderId: '297260992136',
    projectId: 'ecorommece-app-kit',
    storageBucket: 'ecorommece-app-kit.appspot.com',
    iosBundleId: 'com.example.ecorommeceAppKit.RunnerTests',
  );
}
